changelog:
  exclude: {}
  categories:
    - title: 'Changes 📦'
      labels:
        - '*'
    - title: 'Dependency Updates 🆙'
      labels:
        - 'dependency :robot:'
        - 'github-action :robot:'
