#!/bin/bash

[[ -d ./build ]] && rm -rf build/
[[ ! -d ./build ]] && mkdir build/

crx pack dist --crx-version number 2 -p key.pem --zip-output build/github-repo-status.zip
# crx pack dist --crx-version number 2 -p key.pem -o build/github-repo-status.crx

[[ -d ./dist ]] && rm -rf dist/
