on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: ci

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        id: npm-cache
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-

      - name: Install Dependencies
        run: npm install --ignore-scripts --pure-lockfile
        if: steps.npm-cache.outputs.cache-hit != 'true'

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
        env:
          CI: true
