on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: ci

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x]

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ matrix.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --ignore-scripts --pure-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - run: yarn test
        env:
          CI: true
