name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CI: true
          
permissions:
  contents: read
  packages: write

jobs:
  publish:
    uses: stoe/policies/.github/workflows/policy-node-publish.yml@main
    with:
      npm: false
      gh: true

  release:
    runs-on: ubuntu-latest

    needs: [publish]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'npm'

      - run: npm install --ignore-scripts --pure-lockfile

      - run: npm run build --if-present

      - uses: softprops/action-gh-release@v1
        with:
          files: build/github-helper.zip
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

