name: publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@stoe'

      # Publish to GitHub Packages
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    runs-on: ubuntu-latest

    needs: [publish]

    permissions: write-all

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          lfs: true

      - uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.x
          cache: 'npm'

      - run: npm install --ignore-scripts --pure-lockfile

      - run: npm run build --if-present
        env:
          CI: true

      - uses: softprops/action-gh-release@v1
        with:
          files: build/github-helper.zip
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
