name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CI: true

permissions:
  contents: read
  packages: write

jobs:
  publish:
    uses: stoe/policies/.github/workflows/policy-node-publish.yml@main
    with:
      npm: false
      gh: true

  release:
    runs-on: ubuntu-latest

    needs: [publish]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          lfs: true

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: 14.x
          cache: 'npm'

      - run: npm install --ignore-scripts --pure-lockfile

      - run: npm run build --if-present

      - uses: softprops/action-gh-release@4c8d8e0ff9dddee0dddd4db3b5910452a3491d3a
        with:
          files: build/github-helper.zip
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

