on:
  push:
    tags:
      - 'v*'

name: release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - run: yarn install
      - run: yarn build
        env:
          CI: true
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: contains(github.ref, 'alpha')
          prerelease: contains(github.ref, 'beta')
      - uses: actions/upload-release-asset@v1
        id: upload-release-asset-zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/github-repo-status.zip
          asset_name: github-repo-status.zip
          asset_content_type: application/zip
      - uses: actions/upload-release-asset@v1
        id: upload-release-asset-crx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/github-repo-status.crx
          asset_name: github-repo-status.crx
          asset_content_type: application/application/x-chrome-extension
