on:
  push:
    tags:
      - 'v*.*.*'

name: release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Setup node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache node modules
        uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-

      - name: Install Dependencies
        run: npm install --ignore-scripts --pure-lockfile

      - name: Build
        run: npm run build --if-present
        env:
          CI: true

      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}

      - name: Upload release archive (zip)
        uses: actions/upload-release-asset@v1
        id: upload-release-asset-zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/github-helper.zip
          asset_name: github-helper.zip
          asset_content_type: application/zip
      # - name: Upload release archive (crx)
      #   uses: actions/upload-release-asset@v1
      #   id: upload-release-asset-crx
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./build/github-helper.crx
      #     asset_name: github-helper.crx
      #     asset_content_type: application/x-chrome-extension
